
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsxutkuqwbzcasybpcxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzeHV0a3Vxd2J6Y2FzeWJwY3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjkzNTIsImV4cCI6MjA2MTI0NTM1Mn0.iwWq5lO2hbmyN4JA1JvLHkSUJXwMH0u4cptrt2ShWYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
